### ISSUE TITLE
font-weight: bold not necessary on h1 and h2s 

### ISSUE THREAD

**Issue by jzhu01** [salcrom/prj-rev-bwfs-dasmoto#1]
Seen here: https://github.com/salcrom/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's_Arts_%26_Crafts/resources/css/index.css#L38

Since the h1 and h2s are bolded by default, you don't need to set them to be bold.

**Comment by salcrom** [comment]
I didn't realized
