### ISSUE TITLE
.container div not necessary 

### ISSUE THREAD

**Issue by jzhu01** [salcrom/prj-rev-bwfs-dasmoto#2]
Seen here: https://github.com/salcrom/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's_Arts_%26_Crafts/resources/css/index.css#L29-L31

No need to have this, seeing as there also isn't a value here.

**Comment by salcrom** [comment]
I was thinking in give a max-width in order to be properly in the screen of a 940px screen desktop but then I forgot to write it.
